name = "Northern Blood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "397bb9f4c7cdebcbfbf855ea410641aa30a82695354203a24ef1f2072398d0e5"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
