name = "Northern Blood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880be26ee0b5eb8a47b4cd1bcdebb1d4666c7cd4c03dc6a98130788c97c69e3e"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"

[options]
datapack-folder = "config/openloader/data"
