name = "Northern Blood"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ff11ba5282c0bf8cf907c4ef0301f9e2716f25322d31dbc49cd579a4e6f261"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
